global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nimbusrun-api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
  - job_name: 'nimbusrun-worker'
    static_configs:
      - targets: ['worker:9091']
  - job_name: 'nimbusrun-scheduler'
    static_configs:
      - targets: ['scheduler:9092']
